environment:
  nodejs_version:
    - "8"
    - "6"
    - "4"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm test

build: off
